refactor if statement

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -125,12 +125,10 @@ runs:
           echo "Expected dist directory to contain bundle.js and universal.bundle.js"; \
           echo "Missing dist/bundle.js"; \
           exit 1; \
-        else \
-          if [ ! -f "dist/universal.bundle.js" ]; then \
-            echo "Expected dist directory to contain bundle.js and universal.bundle.js"; \
-            echo "Missing dist/universal.bundle.js"; \
-            exit 1; \
-          fi;
+        elif [ ! -f "dist/universal.bundle.js" ]; then \
+          echo "Expected dist directory to contain bundle.js and universal.bundle.js"; \
+          echo "Missing dist/universal.bundle.js"; \
+          exit 1; \
         fi;
 
     - name: Run Tests
