add multi site recommendation template sync

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -45,6 +45,9 @@ inputs:
   GITHUB_BOT_TOKEN:
     description: 'Github user PAT token for posting lighthouse results in pull request comments'
     required: false
+  secrets:
+    description: 'Secrets encoded via toJSON. Expected if project has multiple siteIds in package.json. Expects repository secret for each key (ie. `WEBSITE_SECRET_KEY_${siteId}`)'
+    required: false
 
 runs:
   using: "composite"
@@ -77,9 +80,33 @@ runs:
         fi;
         echo "::set-output name=branch::$branch"
         echo "Using branch: $branch"
-        siteId=`jq -r '.searchspring.siteId' < package.json`
-        echo "::set-output name=siteId::$siteId"
-        echo "Using siteId: $siteId"
+        
+        secrets=`echo "${{ toJSON(inputs.secrets) }}"`;
+        echo "::set-output name=secrets::$secrets";
+        echo "Using secrets: $secrets";
+
+        siteId_Type=`jq -r '.searchspring.siteId | type' < package.json`;
+        echo "::set-output name=siteId_Type::$siteId_Type"; \
+
+        if [ $siteId_Type = 'string' ]; then \
+          echo "siteId is a string"; \
+          siteId=`jq -r '.searchspring.siteId' < package.json`; \
+          echo "::set-output name=siteId::$siteId"; \
+          echo "Using siteId: $siteId"; \
+        elif [ $siteId_Type = 'object' ]; then \
+          echo "siteId is an object"; \
+          siteIds=`jq -r '.searchspring.siteId | keys | join(",")' < package.json`; \
+          echo "::set-output name=siteIds::$siteIds"; \
+          echo "Using siteIds: $siteIds"; \
+
+          siteNames=`jq -r '[.searchspring.siteId[].name] | join(",")' < package.json`; \
+          echo "::set-output name=siteNames::$siteNames"; \
+          echo "Using siteNames: $siteNames"; \
+        else \
+          echo "Cannot determine project siteId from package.json"; \
+          exit 1; \
+        fi;
+
         pullRequestID=${{ github.event.pull_request.number }}
         echo "::set-output name=pullRequestID::$pullRequestID"
         echo "Using pullRequestID: $pullRequestID"
@@ -89,22 +116,6 @@ runs:
         startTime=`date -u +%s`
         echo "::set-output name=startTime::$startTime"
         echo "Using startTime: $startTime"
-    
-    - name: Authenticate siteId and secretKey
-      id: authenticate
-      shell: bash
-      working-directory: repository
-      run: |
-        if curl https://smc-config-api.kube.searchspring.io/api/customer/${{ steps.variables.outputs.siteId }}/verify \
-        -X POST \
-        -d '{"name":"${{ steps.variables.outputs.repository }}"}' \
-        -H "Authorization: ${{ inputs.secretKey }}" \
-        -H "accept: application/json" -H "User-Agent:" \
-        | jq .message \
-        | grep -q 'success'; \
-        then echo 'siteId matches account secretKey!'; \
-        else echo 'Authentication failed! Please ensure siteId, secretKey and repository name are correct.'; exit 1; \
-        fi;
 
     - name: Setup Node
       id: setup-node
@@ -113,6 +124,20 @@ runs:
         node-version: 16
         registry-url: 'https://npm.pkg.github.com'
         scope: '@searchspring'
+
+    - name: Authenticate siteId and secretKey
+      id: authenticate
+      shell: bash
+      run: |
+        npm install
+        node scripts/smc/verify.js \
+          --siteId_Type "${{ steps.variables.outputs.siteId_Type }}" \
+          --siteId "${{ steps.variables.outputs.siteId }}" \
+          --repository "${{ steps.variables.outputs.repository }}" \
+          --secretKey "${{ inputs.secretKey }}" \
+          --siteIds "${{ steps.variables.outputs.siteIds }}" \
+          --siteNames "${{ steps.variables.outputs.siteNames }}" \
+          --secrets-ci '${{ steps.variables.outputs.secrets }}';
 
     - name: Cache node_modules
       id: cache
@@ -136,7 +161,6 @@ runs:
         NODE_AUTH_TOKEN: ${{ inputs.NODE_AUTH_TOKEN }}
       run: |
         npm install
-        npm install -g snapfu
 
     - name: Build Bundle
       id: build
@@ -176,8 +200,12 @@ runs:
       shell: bash
       working-directory: repository
       run: |
+        npm install -g "https://github.com/searchspring/snapfu.git#recs-multi-site" # TODO remove this
+
         if [ ${{ steps.variables.outputs.branch }} = production ]; then \
-          snapfu recs sync --secret-key ${{ inputs.secretKey }}; \
+          snapfu recs sync \
+            --secret-key "${{ inputs.secretKey }}" \
+            --secrets-ci '${{ steps.variables.outputs.secrets }}';
         else \
           echo 'skipping snapfu recs sync for ${{ steps.variables.outputs.branch }} branch'; \
         fi; \
@@ -236,8 +264,18 @@ runs:
         if [ "${{ github.event_name }}" = "pull_request" ]; then \
           echo "skipping upload of 'dist' and 'public' directories to S3 for pull_request action triggers"; \
         else \
-          aws s3 sync --cache-control max-age=1800 --acl public-read dist s3://${{ inputs.aws-s3-bucket-name }}/${{ steps.variables.outputs.siteId }}/${{ steps.variables.outputs.branch }}
-          aws s3 sync --cache-control max-age=1800 --acl public-read public s3://${{ inputs.aws-s3-bucket-name }}/${{ steps.variables.outputs.siteId }}/${{ steps.variables.outputs.branch }}
+          if [ '${{ steps.variables.outputs.siteId_Type }}' = 'string' ]; then \
+            aws s3 sync --cache-control max-age=1800 --acl public-read dist s3://${{ inputs.aws-s3-bucket-name }}/${{ steps.variables.outputs.siteId }}/${{ steps.variables.outputs.branch }}
+            aws s3 sync --cache-control max-age=1800 --acl public-read public s3://${{ inputs.aws-s3-bucket-name }}/${{ steps.variables.outputs.siteId }}/${{ steps.variables.outputs.branch }}
+          elif [ '${{ steps.variables.outputs.siteId_Type }}' = 'object' ]; then \
+            echo "${{ steps.variables.outputs.siteIds }}" | tr , '\n' | while read siteId
+              do
+                echo "Copying files to S3 for siteId $siteId"
+                aws s3 sync --cache-control max-age=1800 --acl public-read dist s3://${{ inputs.aws-s3-bucket-name }}/$siteId/${{ steps.variables.outputs.branch }}
+                aws s3 sync --cache-control max-age=1800 --acl public-read public s3://${{ inputs.aws-s3-bucket-name }}/$siteId/${{ steps.variables.outputs.branch }}
+              done;
+          fi;
+
         fi;
         if [ -f tests/lighthouse/runs/manifest.json ]; then aws s3 sync --acl public-read tests/lighthouse/runs s3://${{ inputs.aws-s3-bucket-name }}/${{ steps.variables.outputs.siteId }}/.lighthouse/${{ steps.variables.outputs.branch }}; fi;
 
@@ -248,35 +286,52 @@ runs:
       env:
         AWS_MAX_ATTEMPTS: 9
       run: |
-        if [ ${{ steps.variables.outputs.branch }} = production ]; then \
-          aws cloudfront create-invalidation --distribution-id ${{ inputs.aws-cloudfront-distribution-id }} --paths "/${{ steps.variables.outputs.siteId }}/*"
-        else \
-          aws cloudfront create-invalidation --distribution-id ${{ inputs.aws-cloudfront-distribution-id }} --paths "/${{ steps.variables.outputs.siteId }}/${{ steps.variables.outputs.branch }}/*"
-          if [ -f tests/lighthouse/runs/manifest.json ]; then aws cloudfront create-invalidation --distribution-id ${{inputs.aws-cloudfront-distribution-id }} --paths "/${{ steps.variables.outputs.siteId }}/.lighthouse/${{ steps.variables.outputs.branch }}/manifest.json"; fi;
+        if [ ${{ steps.variables.outputs.branch }} = production ]; then
+          if [ '${{ steps.variables.outputs.siteId_Type }}' = 'string' ]; then
+            aws cloudfront create-invalidation --distribution-id ${{ inputs.aws-cloudfront-distribution-id }} --paths "/${{ steps.variables.outputs.siteId }}/*"
+          elif [ '${{ steps.variables.outputs.siteId_Type }}' = 'object' ]; then
+            echo "${{ steps.variables.outputs.siteIds }}" | tr , '\n' | while read siteId
+              do
+                echo "Invalidating files for siteId $siteId"
+                aws cloudfront create-invalidation --distribution-id ${{ inputs.aws-cloudfront-distribution-id }} --paths "/$siteId/*"
+              done
+          fi
+        else
+          if [ '${{ steps.variables.outputs.siteId_Type }}' = 'string' ]; then
+            aws cloudfront create-invalidation --distribution-id ${{ inputs.aws-cloudfront-distribution-id }} --paths "/${{ steps.variables.outputs.siteId }}/${{ steps.variables.outputs.branch }}/*"
+            if [ -f tests/lighthouse/runs/manifest.json ]; then aws cloudfront create-invalidation --distribution-id ${{inputs.aws-cloudfront-distribution-id }} --paths "/${{ steps.variables.outputs.siteId }}/.lighthouse/${{ steps.variables.outputs.branch }}/manifest.json"; fi
+          elif [ '${{ steps.variables.outputs.siteId_Type }}' = 'object' ]; then
+            echo "${{ steps.variables.outputs.siteIds }}" | tr , '\n' | while read siteId
+              do
+                echo "Invalidating files for siteId $siteId on branch ${{ steps.variables.outputs.branch }}"
+                aws cloudfront create-invalidation --distribution-id ${{ inputs.aws-cloudfront-distribution-id }} --paths "/$siteId/${{ steps.variables.outputs.branch }}/*"
+                if [ -f tests/lighthouse/runs/manifest.json ]; then aws cloudfront create-invalidation --distribution-id ${{inputs.aws-cloudfront-distribution-id }} --paths "/$siteId/.lighthouse/${{ steps.variables.outputs.branch }}/manifest.json"; fi
+              done
+          fi
         fi
 
-    - run: |
-        npx -y jjo \
-          timestamp=$(date -u +"%FT%TZ" | tr -d '\n') \
-          type=snap-action \
-          data=$(npx -y jjo \
-            conclusion=${{ github.action_status }} \
-            duration=$(expr $(date -u +%s) - ${{ steps.variables.outputs.startTime }} ) \
-            repository=${{ steps.variables.outputs.repository }} \
-            repositoryOwner=${{ github.repository_owner }} \
-            branch=${{ steps.variables.outputs.branch }} \
-            baseRef=${{ github.base_ref }} \
-            actor=${{ github.actor }} \
-            eventName=${{ github.event_name }} \
-            job=${{ github.job }} \
-            url='https://github.com/${{ github.repository_owner }}/${{ steps.variables.outputs.repository }}/actions/runs/${{ github.run_id }}' \
-            runAttempt=${{ github.run_attempt }} \
-            failedStep='${{ steps.checkout-repo.conclusion == 'Failure' && 'checkout-repo' || steps.configure-aws.conclusion == 'Failure' && 'configure-aws' || steps.variables.conclusion == 'Failure' && 'variables' || steps.authenticate.conclusion == 'Failure' && 'authenticate' || steps.setup-node.conclusion == 'Failure' && 'setup-node' || steps.cache.conclusion == 'Failure' && 'cache' || steps.install.conclusion == 'Failure' && 'install' || steps.build.conclusion == 'Failure' && 'build' || steps.test.conclusion == 'Failure' && 'test' || steps.snapfu-recs-sync.conclusion == 'Failure' && 'snapfu-recs-sync' || steps.lighthouse.conclusion == 'Failure' && 'lighthouse' || steps.pr-comment.conclusion == 'Failure' && 'pr-comment' || steps.s3-upload.conclusion == 'Failure' && 's3-upload' || steps.lighthouse-metrics.conclusion == 'Failure' && 'lighthouse-metrics' || steps.invalidation.conclusion == 'Failure' && 'invalidation' || steps.metrics.conclusion == 'Failure' && 'metrics' || ''}}' \
-          ) \
-        > SnapAction-${{ steps.variables.outputs.repository }}-${{ github.event_name }}-$(date -u +"%Y_%m_%d_%H%M").json && \
-        cat ./SnapAction*.json && \
-        aws s3 cp --region us-east-1 ./SnapAction*.json s3://datawarehouse-stage/team-metrics-import/
-      id: metrics
-      shell: bash
-      if: always()
+    # - run: |
+    #     npx -y jjo \
+    #       timestamp=$(date -u +"%FT%TZ" | tr -d '\n') \
+    #       type=snap-action \
+    #       data=$(npx -y jjo \
+    #         conclusion=${{ github.action_status }} \
+    #         duration=$(expr $(date -u +%s) - ${{ steps.variables.outputs.startTime }} ) \
+    #         repository=${{ steps.variables.outputs.repository }} \
+    #         repositoryOwner=${{ github.repository_owner }} \
+    #         branch=${{ steps.variables.outputs.branch }} \
+    #         baseRef=${{ github.base_ref }} \
+    #         actor=${{ github.actor }} \
+    #         eventName=${{ github.event_name }} \
+    #         job=${{ github.job }} \
+    #         url='https://github.com/${{ github.repository_owner }}/${{ steps.variables.outputs.repository }}/actions/runs/${{ github.run_id }}' \
+    #         runAttempt=${{ github.run_attempt }} \
+    #         failedStep='${{ steps.checkout-repo.conclusion == 'Failure' && 'checkout-repo' || steps.configure-aws.conclusion == 'Failure' && 'configure-aws' || steps.variables.conclusion == 'Failure' && 'variables' || steps.authenticate.conclusion == 'Failure' && 'authenticate' || steps.setup-node.conclusion == 'Failure' && 'setup-node' || steps.cache.conclusion == 'Failure' && 'cache' || steps.install.conclusion == 'Failure' && 'install' || steps.build.conclusion == 'Failure' && 'build' || steps.test.conclusion == 'Failure' && 'test' || steps.snapfu-recs-sync.conclusion == 'Failure' && 'snapfu-recs-sync' || steps.lighthouse.conclusion == 'Failure' && 'lighthouse' || steps.pr-comment.conclusion == 'Failure' && 'pr-comment' || steps.s3-upload.conclusion == 'Failure' && 's3-upload' || steps.lighthouse-metrics.conclusion == 'Failure' && 'lighthouse-metrics' || steps.invalidation.conclusion == 'Failure' && 'invalidation' || steps.metrics.conclusion == 'Failure' && 'metrics' || ''}}' \
+    #       ) \
+    #     > SnapAction-${{ steps.variables.outputs.repository }}-${{ github.event_name }}-$(date -u +"%Y_%m_%d_%H%M").json && \
+    #     cat ./SnapAction*.json && \
+    #     aws s3 cp --region us-east-1 ./SnapAction*.json s3://datawarehouse-stage/team-metrics-import/
+    #   id: metrics
+    #   shell: bash
+    #   if: always()
     
