adding secrets to development action

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -72,54 +72,55 @@ runs:
     #     aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
     #     aws-region: ${{ inputs.aws-region }}
         
-    # - name: Extract Variables
-    #   id: variables
-    #   shell: bash
-    #   working-directory: repository
-    #   run: |
-    #     if [ "${{ github.event_name }}" = "pull_request" ]; then \
-    #       branch=${{ github.head_ref }};
-    #     else
-    #       branch=`echo ${GITHUB_REF#refs/heads/}`;
-    #     fi;
-    #     echo "::set-output name=branch::$branch"
-    #     echo "Using branch: $branch"
+    - name: Extract Variables
+      id: variables
+      shell: bash
+      working-directory: repository
+      run: |
+        node ../scripts/utils/logStep.js --step "Extract Variables" --message "extracting variables from action inputs";
+        if [ "${{ github.event_name }}" = "pull_request" ]; then \
+          branch=${{ github.head_ref }};
+        else
+          branch=`echo ${GITHUB_REF#refs/heads/}`;
+        fi;
+        echo "::set-output name=branch::$branch"
+        echo "Using branch: $branch"
 
-    #     secrets=`echo '${{ inputs.secrets }}' | jq -c .`;
-    #     echo "::set-output name=secrets::$secrets";
-    #     echo "Using secrets: $secrets";
+        secrets=`echo '${{ inputs.secrets }}' | jq -c .`;
+        echo "::set-output name=secrets::$secrets";
+        echo "Using secrets: $secrets";
 
-    #     siteId_Type=`jq -r '.searchspring.siteId | type' < package.json`;
-    #     echo "::set-output name=siteId_Type::$siteId_Type"; \
+        siteId_Type=`jq -r '.searchspring.siteId | type' < package.json`;
+        echo "::set-output name=siteId_Type::$siteId_Type"; \
 
-    #     if [ $siteId_Type = 'string' ]; then \
-    #       echo "siteId is a string"; \
-    #       siteId=`jq -r '.searchspring.siteId' < package.json`; \
-    #       echo "::set-output name=siteId::$siteId"; \
-    #       echo "Using siteId: $siteId"; \
-    #     elif [ $siteId_Type = 'object' ]; then \
-    #       echo "siteId is an object"; \
-    #       siteIds=`jq -r '.searchspring.siteId | keys_unsorted | join(",")' < package.json`; \
-    #       echo "::set-output name=siteIds::$siteIds"; \
-    #       echo "Using siteIds: $siteIds"; \
+        if [ $siteId_Type = 'string' ]; then \
+          echo "siteId is a string"; \
+          siteId=`jq -r '.searchspring.siteId' < package.json`; \
+          echo "::set-output name=siteId::$siteId"; \
+          echo "Using siteId: $siteId"; \
+        elif [ $siteId_Type = 'object' ]; then \
+          echo "siteId is an object"; \
+          siteIds=`jq -r '.searchspring.siteId | keys_unsorted | join(",")' < package.json`; \
+          echo "::set-output name=siteIds::$siteIds"; \
+          echo "Using siteIds: $siteIds"; \
 
-    #       siteNames=`jq -r '[.searchspring.siteId[].name] | join(",")' < package.json`; \
-    #       echo "::set-output name=siteNames::$siteNames"; \
-    #       echo "Using siteNames: $siteNames"; \
-    #     else \
-    #       echo "Cannot determine project siteId from package.json"; \
-    #       exit 1; \
-    #     fi;
+          siteNames=`jq -r '[.searchspring.siteId[].name] | join(",")' < package.json`; \
+          echo "::set-output name=siteNames::$siteNames"; \
+          echo "Using siteNames: $siteNames"; \
+        else \
+          echo "Cannot determine project siteId from package.json"; \
+          exit 1; \
+        fi;
 
-    #     pullRequestID=${{ github.event.pull_request.number }}
-    #     echo "::set-output name=pullRequestID::$pullRequestID"
-    #     echo "Using pullRequestID: $pullRequestID"
-    #     repository=`git config --get remote.origin.url | grep -Eo "[^\/]+$" | grep -Eo "(.+)[^(\.git)]"`
-    #     echo "::set-output name=repository::$repository"
-    #     echo "Using repository: $repository"
-    #     startTime=`date -u +%s`
-    #     echo "::set-output name=startTime::$startTime"
-    #     echo "Using startTime: $startTime"
+        pullRequestID=${{ github.event.pull_request.number }}
+        echo "::set-output name=pullRequestID::$pullRequestID"
+        echo "Using pullRequestID: $pullRequestID"
+        repository=`git config --get remote.origin.url | grep -Eo "[^\/]+$" | grep -Eo "(.+)[^(\.git)]"`
+        echo "::set-output name=repository::$repository"
+        echo "Using repository: $repository"
+        startTime=`date -u +%s`
+        echo "::set-output name=startTime::$startTime"
+        echo "Using startTime: $startTime"
 
     - name: Setup Node
       id: setup-node
@@ -129,32 +130,33 @@ runs:
         registry-url: 'https://npm.pkg.github.com'
         scope: '@searchspring'
 
-    # - name: Cache node_modules
-    #   id: cache
-    #   uses: actions/cache@v2
-    #   env:
-    #     cache-name: cache-node-modules
-    #   with:
-    #     # npm cache files are stored in `~/.npm` on Linux/macOS
-    #     path: ~/.npm
-    #     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
-    #     restore-keys: |
-    #       ${{ runner.os }}-build-${{ env.cache-name }}-
-    #       ${{ runner.os }}-build-
-    #       ${{ runner.os }}-
+    - name: Cache node_modules
+      id: cache
+      uses: actions/cache@v2
+      env:
+        cache-name: cache-node-modules
+      with:
+        # npm cache files are stored in `~/.npm` on Linux/macOS
+        path: ~/.npm
+        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
+        restore-keys: |
+          ${{ runner.os }}-build-${{ env.cache-name }}-
+          ${{ runner.os }}-build-
+          ${{ runner.os }}-
 
-    # - name: Authenticate siteId and secretKey
-    #   id: authenticate
-    #   shell: bash
-    #   run: |
-    #     node scripts/smc/verify.js \
-    #       --siteId_Type "${{ steps.variables.outputs.siteId_Type }}" \
-    #       --siteId "${{ steps.variables.outputs.siteId }}" \
-    #       --repository "${{ steps.variables.outputs.repository }}" \
-    #       --secretKey "${{ inputs.secretKey }}" \
-    #       --siteIds "${{ steps.variables.outputs.siteIds }}" \
-    #       --siteNames "${{ steps.variables.outputs.siteNames }}" \
-    #       --secrets-ci '${{ steps.variables.outputs.secrets }}';
+    - name: Authenticate siteId and secretKey
+      id: authenticate
+      shell: bash
+      run: |
+        node scripts/utils/logStep.js --step "Authenticate Searchspring Account" --message "verifying siteId and secretKey"
+        node scripts/smc/verify.js \
+          --siteId_Type "${{ steps.variables.outputs.siteId_Type }}" \
+          --siteId "${{ steps.variables.outputs.siteId }}" \
+          --repository "${{ steps.variables.outputs.repository }}" \
+          --secretKey "${{ inputs.secretKey }}" \
+          --siteIds "${{ steps.variables.outputs.siteIds }}" \
+          --siteNames "${{ steps.variables.outputs.siteNames }}" \
+          --secrets-ci '${{ steps.variables.outputs.secrets }}';
 
     - name: Install Packages
       id: install
@@ -163,6 +165,7 @@ runs:
       env:
         NODE_AUTH_TOKEN: ${{ inputs.NODE_AUTH_TOKEN }}
       run: |
+        node ../scripts/utils/logStep.js --step "Install Packages" --message "installing node packages"
         npm ci
 
     - name: Build Bundle
@@ -170,6 +173,7 @@ runs:
       shell: bash
       working-directory: repository
       run: |
+        node ../scripts/utils/logStep.js --step "Build Bundle" --message "building the Snap bundle"
         npm run build
         if [ ! -f "dist/bundle.js" ]; then \
           echo "Expected dist directory to contain bundle.js and universal.bundle.js"; \
@@ -181,22 +185,23 @@ runs:
           exit 1; \
         fi;
 
-    # - name: Run Tests
-    #   id: test
-    #   shell: bash
-    #   working-directory: repository
-    #   run: |
-    #     if [ "${{ steps.variables.outputs.pullRequestID }}" = "" ]; then \
-    #       if [ ${{ inputs.skipTests }} = true ]; then \
-    #         echo 'skipping tests due to skipTests flag'; 
-    #       elif [ ${{ steps.variables.outputs.branch }} = production ]; then \
-    #         echo "skipping tests for push triggers to production"; \
-    #       else \
-    #         npm run test; \
-    #       fi; \
-    #     else \
-    #       echo 'skipping tests for pull_request triggers'; \
-    #     fi;
+    - name: Run Tests
+      id: test
+      shell: bash
+      working-directory: repository
+      run: |
+        node ../scripts/utils/logStep.js --step "Run Tests" --message "running Cypress testing on bundle"
+        if [ "${{ steps.variables.outputs.pullRequestID }}" = "" ]; then \
+          if [ ${{ inputs.skipTests }} = true ]; then \
+            echo 'skipping tests due to skipTests flag'; 
+          elif [ ${{ steps.variables.outputs.branch }} = production ]; then \
+            echo "skipping tests for push triggers to production"; \
+          else \
+            npm run test; \
+          fi; \
+        else \
+          echo 'skipping tests for pull_request triggers'; \
+        fi;
     
     # - name: Snapfu Recs Sync
     #   id: snapfu-recs-sync
@@ -353,3 +358,9 @@ runs:
     #   shell: bash
     #   if: always()
     
+    - name: Log Summary
+      id: summary
+      shell: bash
+      if: always()
+      run: |
+          node scripts/utils/logSummary.js --steps '${{ toJSON(steps) }}'
